import { format } from 'date-fns'
import { zhCN } from 'date-fns/locale'
import { useWorkspaceItems } from '../items/useWorkspaceItems'
import './today.css'

export function TodayPage() {
  const today = format(new Date(), 'yyyy-MM-dd'); const { items, isLoading } = useWorkspaceItems(); const todayItems = items.filter((item) => item.schedule_date === today); const focus = items.filter((item) => item.is_focus && item.status !== 'done').slice(0, 3); const untimed = todayItems.filter((item) => !item.schedule_start_time); const timed = todayItems.filter((item) => item.schedule_start_time).sort((a,b) => (a.schedule_start_time ?? '').localeCompare(b.schedule_start_time ?? '')); const inbox = items.filter((item) => !item.parent_id && !item.schedule_granularity && item.kind === 'task')
  if (isLoading) return <p role="status">正在准备今天…</p>
  return <div className="today-page"><header className="section-heading"><div><p>{format(new Date(), 'M月d日 EEEE', { locale: zhCN })}</p><h1>今天，慢慢来。</h1><span>先把最重要的一小步完成。</span></div></header><section className="today-focus"><header><strong>今日重点</strong><span>{focus.length}/3</span></header><div>{focus.length ? focus.map((item) => <article key={item.id}><small>{item.parent_id ? '来自目标' : '独立任务'}</small><strong>{item.title}</strong></article>) : <p>从今天的任务里选出最多三件重点。</p>}</div></section><div className="today-layout"><section className="today-timeline"><header><strong>今天的时间</strong><small>没有具体时间的任务放在顶部</small></header><div className="today-untimed">{untimed.map((item) => <span key={item.id}>{item.title}</span>)}</div>{Array.from({ length: 13 }, (_, i) => i + 8).map((hour) => <div className="today-hour" key={hour}><time>{String(hour).padStart(2,'0')}:00</time><div>{timed.filter((item) => Number(item.schedule_start_time?.slice(0,2)) === hour).map((item) => <article key={item.id}><strong>{item.title}</strong><small>{item.schedule_start_time?.slice(0,5)}</small></article>)}</div></div>)}</section><aside className="today-rail"><header><strong>收集箱</strong><span>{inbox.length}</span></header>{inbox.length ? inbox.map((item) => <article key={item.id}>{item.title}</article>) : <p>临时记下的事情会在这里等你整理。</p>}</aside></div></div>
}
